# Generated by Django 3.1 on 2020-08-31 21:02

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=30)),
                ('duration', models.FloatField()),
            ],
            managers=[
                ('course', django.db.models.manager.Manager()),
            ],
        ),
    ]
